steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 
    'gcr.io/gbd-dash/nikitiusivanov/dash_app', 
    '.'
  ]

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'gcr.io/gbd-dash/nikitiusivanov/dash_app'
  ]

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/gbd-dash/gbd_app', '--region', 'us-central1']
images:
- gcr.io/gbd-dash/gbd_app